### ISSUE TITLE
Especificação de endpoints REST

### ISSUE THREAD

**Issue by manoelcampos** [ifto-palmas/aglomerou#10]
Especificar endpoints REST para consumo pelo app, usando swagger (implementação da especificação Open API) para Node. 

A biblioteca [swagger-node](https://github.com/swagger-api/swagger-node) tem apresentado problemas com as versões mais novas do Node. Mesmo o quickstart example não funciona.
Então, usar as seguintes bibliotecas:
- [swagger-ui-express](https://github.com/scottie1984/swagger-ui-express): Habilitar a Swagger UI com o expressjs para exibir e documentar os endpoints
- [swagger-jsdoc](https://github.com/Surnet/swagger-jsdoc): Permitir gerar automaticamente a documentação Swagger apenas documentando as rotas com [JSDoc](https://jsdoc.app)

## Links 

- [Tutorial](https://levelup.gitconnected.com/swagger-time-to-document-that-express-api-you-built-9b8faaeae563)
- [Swagger UI Express Demo](https://github.com/manoelcampos/swagger-ui-express-demo)

## Especificação dos Endpoints

A implementação de fato deve ser feita em outras issues.
Basicamente deve-se configurar as rotas no expressjs.

Alguns endpoints sugeridos (baseados em #9):

| Método HTTP |URI| Descrição
|---------------|--- |---------------
| POST | /usuario | Cadastrar usuário para acesso administrativo ao dashboard web
| GET | /usuario/{email}/{hash_senha} | Obter token de autenticação para usuário logar no dashboard usando JSON Web Token (JWT)
| POST | /dispositivo | Cadastrar dispositivo usando o app
| GET | /dispositivo/total | Total de dispositivos (pessoas) usando o app
| POST | /localizacao/usuario/{dispositivo}/{latitude,longitude} | Inserir localização atual do usuário
| GET | /localizacao/tempo-medio-permanencia/{local} | Tempo médio geral ou mensal. Deve-se analisar se o nome do local será armazenado ou sempre obteremos a partir da latitude/longitude. Fazer o reverse geocoding o tempo todo possivelmente será uma operação custosa.
| GET | /localizacao/media-pessoas/{local} | Média de pessoas geral ou mensal
| GET | /localizacao/frequencia-pessoas/{local} |  Frequência de pessoas por hora do dia (geral e mensal)
| GET | /localizacao/mais-frequentados/{local} | Locais mais frequentados (geral ou mensal)
| GET | /noticias | Obter feed das últimas notícias em formato RSS (que pode ser usado em outras aplicações)

# Issues Relacionados

- #9

**Comment by silvioantonio** [comment]
Ola professor, 
ja posso começar a fazer a minha issue seguindo esses endpoints?

**Comment by manoelcampos** [comment]
Olá @silvioantonio,
Desculpa não ter olhado antes, realmente o tempo tá curto.
A estrutura básica já foi definida usando express, então é só seguir este modelo aqui.
O que tenho que fazer é incluir o swagger para documentar a API.
Logo, pode iniciar sua issue.

**Comment by silvioantonio** [comment]
blz, vou iniciar assim que possivel entao.
