### ISSUE TITLE
Dados do usuário não estão sendo atualizados corretamente.

### ISSUE THREAD

**Issue by manoelcampos** [ifto-palmas/aglomerou#111]
- Usuário deve ser atualizado pelo id, não email
- Não deve-se alterar a data de cadastro

**Comment by silvioantonio** [comment]
Hummm... eu acabei escolhendo essa forma de fazer porque geralmente o email é a como uma chave unica para validação....
no sql eu devria ter feita a condição por id......

**Comment by manoelcampos** [comment]
Mas lembra que o usuário pode alterar o email, então não dá pra usá-lo para localizar o cadastro.

**Comment by silvioantonio** [comment]
entendo....eu devia ter pensado nisso na montagem do sql de alteração...
