### ISSUE TITLE
Usar HTTP 422 para dados de entrada inválidos

### ISSUE THREAD

**Issue by manoelcampos** [ifto-palmas/aglomerou#116]
Quando um dado fornecido pelo usuário é inválido, deve-se usar erro HTTP 422 e não 400.
400 indica que a requisição está incorreta, mas este não é o caso. 
A requisição foi bem formatada, mas o valor para um determinado parâmetro é inválido.

**Comment by manoelcampos** [comment]
@silvioantonio para conhecimento

**Comment by silvioantonio** [comment]
Eu pesquisei muito sobre as respostas http, mas no momento havia achado que a 400 serviria para esse proposito...
Tanto o site do mozilla quando w3 mostram as mesmas respostas..eu nao cheguei a entrar no ee para verificar outras possibilidades...
Mas agora estou sabendo rsrs

**Comment by manoelcampos** [comment]
As vezes é questão de interpretação. A [wikipedia](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#4xx_Client_errors) mostra uma lista mais detalhada. O 400 é um erro mais genérico.
