### ISSUE TITLE
Configurar backend para acesso ao Postgres com pool de conexões

### ISSUE THREAD

**Issue by manoelcampos** [ifto-palmas/aglomerou#12]
- Usar módulo [node-postgres](https://node-postgres.com) (página com exemplo de conexão) com o modelo async/await para tornar o código mais legível. 
- Usar o [pool de conexões](https://node-postgres.com/api/pool/) do modulo. 
- [Definir configuração de acesso ao banco como variáveis de ambiente](https://blog.rocketseat.com.br/variaveis-ambiente-nodejs/), para evitar publicar possíveis informações sensíveis.

**Comment by silvioantonio** [comment]
Pode nao paracer, mas essa issue se tornou um grande desafio..
Felizmente tudo tem solução.
:)

**Comment by manoelcampos** [comment]
Hehehe, vai reportando os problemas.
