### ISSUE TITLE
A localização não é enviada quando o app não tá sendo exibido

### ISSUE THREAD

**Issue by manoelcampos** [ifto-palmas/aglomerou#134]
Mesmo que o app esteja aberto mas não esteja sendo exibido, a localização para de ser enviada.
Verificar se pra que continue enviando é preciso implementar um serviço pra ficar em execução. Quando a tela do celular tá desligada também não envia. Possivelmente só resolve com a implementação de um serviço no app.

**Comment by ragirfernando** [comment]
Então nosso app vai ter que roda em segundo plano.

**Comment by ragirfernando** [comment]
Posso implementar para enviar a localização em segundo plano.

**Comment by manoelcampos** [comment]
Isso. Neste caso, é importante que o app fique o ícone na barra de notificações
