### ISSUE TITLE
Implementar endpoints REST para inserir e obter localizacao

### ISSUE THREAD

**Issue by manoelcampos** [ifto-palmas/aglomerou#14]
| Método HTTP |URI| Descrição
|---------------|--- |---------------
| GET | /localizacao/{dispositivo} | Obter última localização do usuário
| POST | /localizacao/usuario/{dispositivo}/{latitude}/{longitude} | Inserir localização atual do usuário

## Issues Relacionadas

- #10

**Comment by manoelcampos** [comment]
@silvioantonio, movi a descrição dos endpoints pra cá.
Cada uma deles seria uma issue separada, mas acabou q faltou tempo pra organizar isso.

**Comment by silvioantonio** [comment]
ei professor, ainda faltam mais endpoints rsrsrs

**Comment by manoelcampos** [comment]
Alterar o endpoint `/localizacao/usuario/{dispositivo}/{latitude}/{longitude}` para `/localizacao/{dispositivo}/{latitude}/{longitude}`

**Comment by manoelcampos** [comment]
@silvioantonio tive que alterar a estrutura do banco. Assim, o mais fácil é apagar o banco e criar novamente. Veja issue #82 para detalhes.
