### ISSUE TITLE
Gerar apk localmente

### ISSUE THREAD

**Issue by manoelcampos** [ifto-palmas/aglomerou#140]
A issue #121 uso o serviço do https://expo.io para gerar o apk do app.
Mas tal serviço depende do AWS Device Farm, gerando uma fila e o build leva uma vida usando a conta gratuita.

## Requisitos para fazer o build do apk localmente

- Android SDK
- Java Development Kit (JDK) 8
- bash

## Links

- [Fazendo build de app expo localmente (documentação oficial do expo.io)](https://docs.expo.io/distribution/turtle-cli/)

**Comment by manoelcampos** [comment]
Corrigiram o [problema](https://github.com/expo/turtle/issues/236) de usar o `app.config.js` no lugar do `app.json`.
Baixei a nova versão do turtle e funcionou perfeitamente.
E o build do apk foi incrivelmente rápido. Não sei se a lentidão era por ter sido o primeiro build.

**Comment by silvioantonio** [comment]
Caraca professor...o pessoal da ferramenta corrigiu esse problema encontrado aqui no projeto.. que fantastico rsrsrs

**Comment by manoelcampos** [comment]
Na verdade outro desenvolvedor tinha reportado, eu apenas comentei lá. Corrigiram em 2 dias 😄
