### ISSUE TITLE
O Lottie está causando crash do app ao inicializar

### ISSUE THREAD

**Issue by manoelcampos** [ifto-palmas/aglomerou#165]
Apesar do Lottie ser uma biblioteca fantástica desenvolvida pelo AirBnb,
o [suporte a ele no expo ainda é Alpha](https://docs.expo.io/versions/latest/sdk/lottie/).
Existe a versão 2 e versão 3. O expo SDK anterior ao 38 suporta apenas o Lottie 2.
O SDK 38 era pra suportar o Lottie 3, apesar do warning no primeiro link acima.

Muitos desenvolvedores têm reclamado dos mesmos problemas:
- https://github.com/react-native-community/lottie-react-native/issues/617
- https://forums.expo.io/t/lottiefiles-crashes-on-android-sdk-34/27018

Foi tentado usar uma versão anterior do Lottie com SDK 37 mas não funcionou também.
Fazendo upgrade pro SDK 38, o app do expo não conseguia conectar no Metro para abrir a aplicação usando o emulador Android.

**Comment by Marq91** [comment]
@manoelcampos How do you solve this? I have the same problem here :c

**Comment by manoelcampos** [comment]
Unfortunately, I didn't have time to check for a fix. 
After upgrading to expo sdk 38, the expo app couldn't connect to the metro server at the dev machine.
But after a while, I found out that clearing the expo app cache on the device makes the expo app work again.
Maybe you could try to upgrade if you haven't yet.

**Comment by manoelcampos** [comment]
At the end, we just removed the Lottie dependency.
