### ISSUE TITLE
Criar estrutura do frontend em react

### ISSUE THREAD

**Issue by manoelcampos** [ifto-palmas/aglomerou#20]
Inicializar um projeto react na pasta frontend já existente.

**Comment by manoelcampos** [comment]
@anabeatrix,
você apenas esqueceu de enviar um Pull Request antes. Isto permite que o código seja revisado antes de ser feito merge. Mas não tem problemas, com o tempo vai pegando o fluxo.

**Comment by anabeatrix** [comment]
Entendi, @manoelcampos!! Tudo bem. 
Percebi isso só depois que tinha enviado as alterações, tentei reverter o push, só que pelo que vi, não é tão simples assim. Mas deixo como está?

**Comment by manoelcampos** [comment]
Tentar reverter corre o risco de você perder algo.
Então não se preocupe. Só se for algo realmente necessário.

**Comment by manoelcampos** [comment]
Outro detalhe, antes de iniciar a issue, lembre de fazer entrar no Branch dev e criar um novo Branch a partir dele executando:

```bash
git checkout dev
git checkout dev -b issue-XXX
```

**Comment by anabeatrix** [comment]
Entendi, bem lembrado!! Obrigada, professor.
