### ISSUE TITLE
Implementar o envio de notificações no app

### ISSUE THREAD

**Issue by manoelcampos** [ifto-palmas/aglomerou#209]
Ao clicar em um ponto no mapa, deve-se obter a localização atual e permitir ao usuário enviar notificação sobre aglomeração naquele local. Ver o vídeo do protótipo para mais detalhes.
Um form deve ser exibido solicitando os dados indicados em #207.
Os campos do form devem ser os mesmos destacados em negrito na issue acima. 

A requisição deve ser enviada conforme #208.

**Comment by Thanyla** [comment]
Esse processo que está descrevendo é o processo de denúncia? 

O usuário pode fazer uma denúncia mesmo não estando no local?

Caso ele só possa fazer estando no local, não seria mais intuitivo ter um botão escrito denunciar na tela?

O endpoint para essa funcionalidade existe?

**Comment by manoelcampos** [comment]
Isso, mas como tínhamos conversado, o termo notificação no lugar de denúncia seria melhor.
O usuário não escolhe o local. A notificação vai pegar a localização atual do usuário, então, ele não pode enviar de um outro local.
A especificação do endpoint já tá pronta, que é a issue #208.
Se você acessar a URL do backend colocando /api-docs no final, vai ver a documentação.
Com isso, já consegue ir implementando.
A implementação do endpoint de fato, está em revisão já (#207)
