### ISSUE TITLE
Definir qual ferramenta a ser usada para o dashboard web e criar estrutura

### ISSUE THREAD

**Issue by manoelcampos** [ifto-palmas/aglomerou#21]
Discutir as alternativas aqui antes de criar estrutura.

**Comment by manoelcampos** [comment]
@anabeatrix vc tinha falado em uma ferramenta para geração de dashboards, isso facilitaria muito. Qual era?

**Comment by anabeatrix** [comment]
> @anabeatrix vc tinha falado em uma ferramenta para geração de dashboards, isso facilitaria muito. Qual era?

As duas que mencionei foram [AdminLTE](https://adminlte.io/) e [Core.iu,](https://coreui.io/react/) recebi boas indicações delas. No caso do Core.ui a vantagem seria que tem p/ node.

**Comment by manoelcampos** [comment]
Então não há o que escolher nesse caso. Precisa apenas verificar se ele tem o que precisamos: permite geração de relatórios e gráficos. Pelo live demo sim. 
É gratuito? Pois vi um botão "buy" lá.

**Comment by anabeatrix** [comment]
> Então não há o que escolher nesse caso. Precisa apenas verificar se ele tem o que precisamos: permite geração de relatórios e gráficos. Pelo live demo sim.
> É gratuito? Pois vi um botão "buy" lá.

Pelo que entendi, é gratuito sim. Tem a versão PRO que, naturalmente, tem mais recursos, mas acredito que a free nos atende. Vou conferir.

**Comment by manoelcampos** [comment]
Blz.

**Comment by manoelcampos** [comment]
@anabeatrix, lembrei que você falou algo sobre o Google Maps,
mas no dashboard não precisamos nos preocupar com isso agora.
O usuário vai visualizar o mapa pelo app.
Se tivermos tempo, no final vemos a possibilidade de inclusão do mapa no dashboard também.

**Comment by anabeatrix** [comment]
Entendi, professor @manoelcampos. Pensei que fosse necessário, então nesse caso é mais simples do que imaginava e a interface vai ficar um pouco diferente do que tínhamos pensando inicialmente, mas não é problema. 
Não fiz nenhum PR ainda, mas estou trabalhando nisso localmente, até amanhã envio.
