### ISSUE TITLE
Criar logo para o app

### ISSUE THREAD

**Issue by manoelcampos** [ifto-palmas/aglomerou#30]
O logo deve ser usado tanto como ícone quanto em outras partes das aplicações.
@anabeatrix ou @ifto-palmas/aglomerou, vocês têm habilidades pra isso? Senão, veremos outra alternativa.

**Comment by anabeatrix** [comment]
Na verdade, nunca fiz nada parecido, mas posso pesquisar e falar com colegas que tem mais experiência com essa parte de design, talvez eles possam me dar orientações e ajuda; até segunda-feira, se não for problema, lhe dou uma resposta quanto a se posso assumir essa responsabilidade ou não. Tudo bem?

**Comment by anabeatrix** [comment]
> O logo deve ser usado tanto como ícone quanto em outras partes das aplicações.
> @anabeatrix ou @ifto-palmas/aglomerou, vocês têm habilidades pra isso? Senão, veremos outra alternativa.

Na verdade, nunca fiz nada parecido, mas posso pesquisar e falar com colegas que tem mais experiência com essa parte de design, talvez eles possam me dar orientações e ajuda; até segunda-feira, se não for problema, lhe dou uma resposta quanto a se posso assumir essa responsabilidade ou não. Tudo bem?

**Comment by manoelcampos** [comment]
Essa pode ser uma das últimas preocupações, só pra irmos vendo alternativas.

**Comment by manoelcampos** [comment]
Ícones adicionados ao drive e serão incluídos aqui apenas os que foram ser utilizados.
