### ISSUE TITLE
Utilizar pack de ORM

### ISSUE THREAD

**Issue by 3runoDesign** [ifto-palmas/aglomerou#49]
algo como o [sequelize](https://github.com/sequelize/sequelize) ou até mesmo o [prisma]( https://github.com/prisma/prisma).

**Comment by manoelcampos** [comment]
Olá @3runoDesign 
Primeiramente muito obrigado pela colaboração.
Um dos membros da equipe até me questionou sobre isso anteriormente. Como o projeto é pequeno e pretendemos ter um MVP o mais rápido possível, acho que incluir um ORM iria apenas complicar as coisas.

Meu background e da equipe é em Java, onde usamos bastante ORM.
Em node nunca usei e realmente não conhecia as soluções.
Gostei bastante dos dois projetos, mas atualmente temos apenas 2 tabelas: dispositivo e localizacao. Não deve aumentar muito mais. Por isso, acho que vamos conseguir maior agilidade no desenvolvimento sem um ORM, até porque a equipe é formada alunos do Instituto Federal do Tocantins, que estão sobrecarregados com as disciplinas que estão cursando.

Mas de qualquer forma, depois que tivermos nosso MVP, podemos repensar sobre isso.
Agradeço mais uma vez e estamos abertos a qualquer tipo de contribuição.

**Comment by 3runoDesign** [comment]
nice man... Entendo! Comentei mesmo pois vi que tem uma vulnerabilidade para SQL-injection attacks. Mas nice man o/

**Comment by manoelcampos** [comment]
Achei que módulos como o do Postgres já resolviam isso usando parâmetros na consulta SQL, no lugar de concatenar variáveis. Se não, é uma preocupação e precisamos ver isso.
No caso de PHP por exemplo, não preciso de um ORM pra evitar SQL Injection.
Valeu pelo aviso.

**Comment by manoelcampos** [comment]
O módulo [node-postgres evita SQL injection com uso de parâmetros na query](https://node-postgres.com/features/queries#Parameterized%20query). As consultas SQL atuais já estão fazendo uso de parâmetros.
