### ISSUE TITLE
Adiciona nodemon como dependência do backend

### ISSUE THREAD

**Issue by manoelcampos** [ifto-palmas/aglomerou#56]
O módulo [nodemon](https://nodemon.io) pode ser instalado globalmente.
No entanto, adicioná-lo como dependência de desenvolvimento permite que todos já tenham tal módulo no projeto facilmente.

O comando `npm start` também deve ser alterado para usar nodemon e depois de executar o servidor uma vez, não precisa mais reiniciá-lo (a não ser que algo muito errado ocorra).

No contêiner Docker o `npm` não é incluído para reduzir o tamanho, iniciando o servidor apenas com o comando `node`, não dependendo das configuração de `start` no `package.json`.

**Comment by manoelcampos** [comment]
Isso vai facilitar o trabalho @silvioantonio

**Comment by silvioantonio** [comment]
Bacana, se vai facilitar o trabalho e melhorar o desempenho, entao sera muito bem vindo rsrs
