### ISSUE TITLE
Definir timeout e configurações adicionais para as conexões com o Postgres

### ISSUE THREAD

**Issue by manoelcampos** [ifto-palmas/aglomerou#88]
Se o banco estiver offline, a aplicação fica esperando indefinidamente.

**Comment by silvioantonio** [comment]
Blzzz.....
Vou aproveitar e verificar a necessidade de redefinir outros atributos do pool tbm

**Comment by manoelcampos** [comment]
Ok. Como é apenas configuração, atualizamos a issue.

**Comment by silvioantonio** [comment]
vou definir alguns parametros entao...o numero maximo de clientes conectados por pool de conexao vou colocar como 20
o cliente sera checado na concexcao com o pool a cada 15 segundos
O tempo para conexao timeout sera de 5 segundos....

**Comment by manoelcampos** [comment]
Blz
