### ISSUE TITLE
Criar as rotas para gerenciamento de usuários do frontend

### ISSUE THREAD

**Issue by manoelcampos** [ifto-palmas/aglomerou#89]
Deve-se apenas definir a especificação das rotas de acordo com a tabela abaixo. A implementação do controller deve ser feita na issue #96 .

| Método HTTP |URI| Descrição
|---------------|--- |---------------
| POST | /usuario | Cadastrar usuário para acesso administrativo ao dashboard web
| PUT | /usuario | Atualizar cadastro do usuário
| DELETE | /usuario/{id} | Excluir cadastro do usuário

**Comment by silvioantonio** [comment]
É para configurar o controller do front end ou criar um endpoint no backend para ser consumido pelo frontend?

**Comment by manoelcampos** [comment]
Criar os endpoints no backend, é que eles vão ser usados apenas pelo frontend, não pelo app.
