### ISSUE TITLE
Analisar como será feita a obtenção de notícias e informações sobre COVID

### ISSUE THREAD

**Issue by manoelcampos** [ifto-palmas/aglomerou#98]
As notícias devem ser obtidas em formato RSS, mesmo que precisem ser compiladas de diferentes fontes. Isso permite o uso de leitores de RSS independentes da app mobile.

### Oficiais
- https://coronavirus.palmas.to.gov.br
- http://www.conass.org.br/painelconasscovid19/ (iniciado depois da ocultação de dados no site do ministério da saúde)
- https://covid.saude.gov.br  (Ministério da Saúde)
- https://transparencia.registrocivil.org.br/especial-covid 
- http://www.dados.gov.br/dataset/notificacao_covid
- https://governoaberto.cgu.gov.br
- http://portal.mec.gov.br/coronavirus/

### Não Oficiais
Podem servir de exemplo e para ver de onde obtém os dados.

- https://brasil.io/dataset/covid19/caso_full/
- http://covid19tst.ifnoar.com.br/brazil

Adicionalmente, notícias podem ser obtidas a partir de uma conta oficial no twitter e monitoramento de hashtag.

Mas a maioria desses sites pode não disponibilizar uma API ou RSS, assim, em último caso, podemos exibir no app e frontend somente alguns links úteis como os acima.

É preciso analisar as possibilidades e discutir aqui antes de iniciar a implementação,
que será dividida em issues para o backend e app.

**Comment by anabeatrix** [comment]
@manoelcampos, como listado, há realmente inúmeras fontes, mas como o objetivo **principal** da aplicação não é apenas fornecer essas informações, talvez não seja necessário buscar dados em muitos e variados sites; ainda assim, é extremamente importante que, ainda que poucas, sejam fontes confiáveis. 
Por isso, acho que vale a pena considerar os [dados](https://github.com/CSSEGISandData/COVID-19) que são fornecidos pela [Universidade Johns Hopkins](https://github.com/CSSEGISandData). As fontes de dados sobre o Brasil que foram usadas por eles:
- Ministério da Saúde: https://covid.saude.gov.br/
-  https://github.com/wcota/covid19br (a vantagem desse, pelo que entendi, é que os dados são obtidos também a partir de informações atualizadas pela conta oficial [@CoronavirusBra1](https://twitter.com/CoronavirusBra1).

Ambas podem ser em conjunto.

Ps: Não sei se atende ao pedido da issue, professor, porque não consegui determinar claramente se se trata de uma API e se podemos consumir esses dados. Qualquer coisa, o senhor corrige e procuro outras fontes ou analiso melhor as que foram sugeridas por você.

**Comment by manoelcampos** [comment]
Bem, na verdade estamos falando de duas coisas diferentes.
Estes links que você mostrou são sobre dados da COVID, mas o que estou falando é a respeito de notícias confiáveis em formato RSS para exibirmos em um feed no app.

**Comment by anabeatrix** [comment]
Certo. Entendi, professor!
Então, realmente a maioria dos sites não disponibiliza uma API nem as notícias em formato RSS, em especial os do Governo, como o do [Ministério da Saúde](https://coronavirus.palmas.to.gov.br).

Alguns que poderiam ser úteis:
- Jornal da USP - https://jornal.usp.br/feed/ (acho que, nesse caso, o problema seria que as informações não são tão relevantes para os usuários do Tocantins).
- Organização Pan-Americana de Saúde - https://www.paho.org/bra/index.php?format=feed&type=rss 
- BBC Brasil - http://feeds.bbc.co.uk/portuguese/ciencia/index.xml (na categoria "Ciência e Saúde", mas com poucas informações específicas sobre COVID).
- Governo Federal CGU - https://www.gov.br/cgu/pt-br/assuntos/noticias/ultimas-noticias/RSS (Erro "Página não encontrada").
- Correio Braziliense - https://www.correiobraziliense.com.br/rss/noticia/ciencia-e-saude/rss.xml 

O que notei é que mesmo os sites que apresentam informações relevantes para aplicação, como o da [OPAS](https://www.paho.org/bra/index.php?format=feed&type=rss), apresentam também muitos outros conteúdos. Como faríamos para filtrar? Pesquisei algumas ferramentas, mas só encontrei opções para o usuário final, por conta própria, fazer a filtragem.

Como o senhor sugeriu, talvez seja uma opção disponibilizar um seção com os links úteis na área de notícias.
- https://saudebrasil.saude.gov.br/ (achei esse interessante, traz artigos que podem ajudar os usuários a lidar com a pandemia e isolamento).

Além de links dos sites com informações oficiais do governo/prefeitura: 
- https://coronavirus.palmas.to.gov.br
- https://covid.saude.gov.br

E de contas oficiais no Twitter: 
- [@CoronavirusBra1](https://twitter.com/CoronavirusBra1)
- [@minsaude](https://twitter.com/minsaude)

**Comment by anabeatrix** [comment]
Enquanto a issue estiver aberta, vou continuar pesquisando mais fontes.

**Comment by manoelcampos** [comment]
> Então, realmente a maioria dos sites não disponibiliza uma API nem as notícias em formato RSS, em especial os do Governo, como o do [Ministério da Saúde](https://coronavirus.palmas.to.gov.br).

Pois é. Daria para vasculhar (scrapping) o HTML, mas é gambiarra, dá muito trabalho e é sucetível a erros. Não vale a pena.

> * Jornal da USP - https://jornal.usp.br/feed/ (acho que, nesse caso, o problema seria que as informações não são tão relevantes para os usuários do Tocantins).

Na verdade, o app tá liberado pra qualquer um usar, logo, podem ser notícias gerais sobre COVID.
Se forem informações específicas da faculdade ou de SP, não vale a pena.

> O que notei é que mesmo os sites que apresentam informações relevantes para aplicação, como o da [OPAS](https://www.paho.org/bra/index.php?format=feed&type=rss), apresentam também muitos outros conteúdos. Como faríamos para filtrar? Pesquisei algumas ferramentas, mas só encontrei opções para o usuário final, por conta própria, fazer a filtragem.

Podemos filtrar por palavras chave como covid, coronavírus.

> 
> Como o senhor sugeriu, talvez seja uma opção disponibilizar um seção com os links úteis na área de notícias.

Bem, então por conta do prazo apertado, vamos fazer a seção de links no lugar de exibir as notícias diretamente.
Junte as fontes governamentais, da imprensa e outras fontes confiáveis para incluirmos.
Os links para as seções de ciência e saúde são ótimos.

**Comment by anabeatrix** [comment]
Certo. Nesse caso, acho que as fontes oficiais não devem ficar de fora:
- https://covid.saude.gov.br/
- https://coronavirus.palmas.to.gov.br/

Além dessas, acho que podemos usar também:
- https://www.bbc.com/portuguese/topics/c340q430z4vt (BBC Brasil, seção Saúde).
- https://exame.com/noticias-sobre/coronavirus/ (Notícias relacionadas no Brasil e mundo).
- https://g1.globo.com/bemestar/coronavirus/ 

E, seria interessante fornecer dicas práticas sobre alimentação, exercícios, etc, para ajudar os usuários:
- https://saudebrasil.saude.gov.br/

Todos as fontes são nacionais, mas incluem notícias de outras países também.

**Comment by manoelcampos** [comment]
Ok. Acho que estão ótimas. Vamos passar pra outra issue então.
